version: "3.7"
services:
  api-database:
    restart: always
    image: "mongo:4.4.17-rc0-focal"
    container_name: "api-database"
    volumes:
      - ../mongo-volume-fivestars:/data/db
    ports:
      - 27017:27017
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api-database