version: "3.7"
services:
  api-database:
    image: "mongo:4.4.6"
    container_name: "api-database"
    environment:
      - MONGO_INITDB_DATABASE=fivestars-customer
      - MONGO_INITDB_ROOT_USERNAME=fivestars-user-db
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./../mongo-volume-fivestars:/data/db
    ports:
      - 27017:27017
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api-database